# Generated by Django 5.0.4 on 2024-06-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_otp_used_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Discount Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='OTP Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP Created at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_trans_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OTP Transaction ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP Used at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='Phone'),
        ),
    ]
