# Generated by Django 5.0.1 on 2024-02-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'Qapıda ödəniş'), (2, 'Kartla ödəniş')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Hazırlanır'), (2, 'Yolda'), (3, 'Çatdırıldı')], default=1)),
                ('address', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'OrderProduct',
                'verbose_name_plural': 'OrderProducts',
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
    ]
