# Generated by Django 5.0.1 on 2024-02-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_payment_type_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
