# Generated by Django 5.0.4 on 2024-05-05 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_note'),
        ('product', '0005_remove_product_in_stock_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_type',
            new_name='payment_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ödənilməyib'), (1, 'Hazırlanır'), (2, 'Yoldadır'), (3, 'Çatdırıldı'), (4, 'Ləğv edildi')], default=0),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.product')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_session_id', models.CharField(blank=True, max_length=255)),
                ('bank_order_id', models.CharField(blank=True, max_length=255)),
                ('installments', models.PositiveSmallIntegerField(default=1)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Gözləmədə'), (1, 'Təsdiqlənib'), (2, 'Rədd edilib'), (3, 'Ləğv edilib')], default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order')),
            ],
            options={
                'verbose_name': 'OrderPayment',
                'verbose_name_plural': 'OrderPayments',
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
