# Generated by Django 5.0.4 on 2024-05-04 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_products_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_session_id', models.CharField(blank=True, max_length=255)),
                ('bank_order_id', models.CharField(blank=True, max_length=255)),
                ('installment', models.PositiveSmallIntegerField(default=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order')),
            ],
            options={
                'verbose_name': 'OrderPayment',
                'verbose_name_plural': 'OrderPayments',
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
    ]
