# Generated by Django 5.0.4 on 2024-05-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_type',
            new_name='payment_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hazırlanır'), (2, 'Yoldadır'), (3, 'Çatdırıldı'), (4, 'Ləğv edildi')], default=1),
        ),
    ]
