# Generated by Django 5.0.4 on 2024-06-22 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_discount'),
        ('product', '0007_alter_productimage_options_alter_productnote_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='orderpayment',
            options={'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Order Payment', 'verbose_name_plural': 'Order Payments'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Qapıda ödəniş'), (2, 'Kartla ödəniş'), (3, 'Borclu ödəniş')], verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ödənilməyib'), (1, 'Hazırlanır'), (2, 'Yoldadır'), (3, 'Çatdırıldı'), (4, 'Ləğv edildi')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='bank_order_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bank Order ID'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='bank_session_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bank Session ID'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='installments',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Installments'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Gözləmədə'), (1, 'Təsdiqlənib'), (2, 'Rədd edilib'), (3, 'Ləğv edilib')], default=0, verbose_name='Status'),
        ),
    ]
