# Generated by Django 5.0.4 on 2024-05-24 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_products_alter_order_options_and_more'),
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to='order.order')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promo.promo')),
            ],
            options={
                'verbose_name': 'PromoUsage',
                'verbose_name_plural': 'PromoUsages',
            },
        ),
    ]
