# Generated by Django 5.0.4 on 2024-06-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_cart_created_at_alter_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-created_at',), 'verbose_name': 'Cart', 'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-created_at',), 'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
    ]
