# Generated by Django 5.0.1 on 2024-02-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_cart_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="discount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
