# Generated by Django 5.0.1 on 2024-04-03 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_recommended',
        ),
    ]
