# Generated by Django 5.0.1 on 2024-01-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'ProductImage', 'verbose_name_plural': 'ProductImages'},
        ),
        migrations.AlterModelOptions(
            name='productnote',
            options={'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'ProductNote', 'verbose_name_plural': 'ProductNotes'},
        ),
    ]
