# Generated by Django 5.0.1 on 2024-04-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_is_recommended"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
