# Generated by Django 5.0.4 on 2024-05-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_in_stock_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_promo',
            field=models.BooleanField(default=True),
        ),
    ]
