# Generated by Django 5.0.4 on 2024-06-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_alter_brand_is_main_alter_brand_name_and_more'),
        ('category', '0004_alter_category_name_alter_category_name_az_and_more'),
        ('product', '0006_product_is_promo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('created_at',), 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='productnote',
            options={'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Product Note', 'verbose_name_plural': 'Product Notes'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brand.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Discount End Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_distributer',
            field=models.BooleanField(default=False, verbose_name='Is Distributer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is New'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_promo',
            field=models.BooleanField(default=True, verbose_name='Is Promo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_note',
            field=models.TextField(blank=True, null=True, verbose_name='Main Note'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_note_az',
            field=models.TextField(blank=True, null=True, verbose_name='Main Note'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_note_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Main Note'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productnote',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='productnote',
            name='text_az',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='productnote',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
