# Generated by Django 5.0.4 on 2024-06-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_created_at_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('position', 'created_at'), 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='productnote',
            options={'ordering': ('position', '-created_at'), 'verbose_name': 'Product Note', 'verbose_name_plural': 'Product Notes'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='productnote',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
