# Generated by Django 5.0.1 on 2024-02-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_az', models.CharField(max_length=255, null=True, unique=True)),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
    ]
