# Generated by Django 5.0.1 on 2024-01-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
