# Generated by Django 5.0.4 on 2024-06-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brand_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is Main'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_az',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Photo'),
        ),
    ]
