# Generated by Django 5.0.1 on 2024-01-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_brand_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
