services:
  app:
    image: ${IMAGE_NAME}:dev
    container_name: ${PROJECT_NAME}_app_dev
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    restart: unless-stopped
    command: python -Wd manage.py runserver 0.0.0.0:${DJANGO_PORT}
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    volumes:
      - .:/app
    env_file:
      - ./config/.env
    environment:
      - IN_DOCKER=1
      - USE_POSTGRES=1
      - POSTGRES_HOST=db
      - DJANGO_ENV=dev
    depends_on:
      - db
    networks:
      - webdata
    healthcheck:
      test: |
        /usr/bin/test $$(
          /usr/bin/curl --fail http://localhost:${DJANGO_PORT}/health/?format=json
          --write-out "%{http_code}" --silent --output /dev/null
        ) -eq 200
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
