# Generated by Django 5.0.1 on 2024-01-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
