# Generated by Django 5.0.4 on 2024-04-26 13:04

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options_category_position'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
