# Generated by Django 5.0.4 on 2024-06-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_created_at_alter_category_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='position',
        ),
    ]
