# Generated by Django 5.0.4 on 2024-06-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freezone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freezoneitem',
            name='image',
        ),
        migrations.CreateModel(
            name='FreezoneItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='freezone/')),
                ('freezone_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='freezone.freezoneitem')),
            ],
            options={
                'verbose_name': 'Freezone Item Image',
                'verbose_name_plural': 'Freezone Item Images',
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
    ]
