# Generated by Django 5.0.1 on 2024-02-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freezone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezoneitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Təsdiq gözləyir'), (1, 'Təsdiqlənib'), (2, 'Rədd edilib')], default=0),
        ),
    ]
