# Generated by Django 5.0.4 on 2024-06-22 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freezone', '0002_remove_freezoneitem_image_freezoneitemimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freezoneitem',
            options={'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Freezone Item', 'verbose_name_plural': 'Freezone Items'},
        ),
        migrations.AlterField(
            model_name='freezoneitem',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='freezoneitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='freezoneitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='freezoneitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Təsdiq gözləyir'), (1, 'Təsdiqlənib'), (2, 'Rədd edilib')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='freezoneitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='freezoneitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='freezoneitemimage',
            name='freezone_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='freezone.freezoneitem', verbose_name='Freezone Item'),
        ),
        migrations.AlterField(
            model_name='freezoneitemimage',
            name='image',
            field=models.ImageField(upload_to='freezone/', verbose_name='Image'),
        ),
    ]
