# Generated by Django 5.0.4 on 2024-06-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freezone', '0004_alter_freezoneitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freezoneitem',
            options={'ordering': ('-created_at',), 'verbose_name': 'Freezone Item', 'verbose_name_plural': 'Freezone Items'},
        ),
        migrations.AlterModelOptions(
            name='freezoneitemimage',
            options={'ordering': ('position', '-created_at'), 'verbose_name': 'Freezone Item Image', 'verbose_name_plural': 'Freezone Item Images'},
        ),
        migrations.AddField(
            model_name='freezoneitemimage',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='freezoneitemimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
