# Generated by Django 5.0.4 on 2024-06-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
    ]
