# Generated by Django 5.0.4 on 2024-06-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appversionconfiguration',
            options={'verbose_name': 'App Version Configuration'},
        ),
    ]
